repo_url: https://github.com/Requisitos-de-Software/2024.2-Grupo06
repo_name: 2024.2-Grupo06
site_name: Meu INSS
nav:
  - Home: index.md
  - Atas:
    - Reunião 1: atas/Reuniao01_23.10.2024.md
    - Reunião 2: atas/Reuniao02_26.10.2024.md
    - Reunião 3: atas/Reuniao03_15.11.2024.md
  - Apresentação:
    - Apresentação 1: apresentacoes/apresentacao1.md
  - Planejamento do Projeto:
    - Heatmap de disponibilidade: planejamento_do_projeto/heatmap-disponibilidade.md
    - Cronograma planejado: planejamento_do_projeto/cronograma_planejado.md
    - Cronograma executado: planejamento_do_projeto/cronograma_executado.md
    - Ferramentas do projeto: planejamento_do_projeto/ferramentas.md
    - Aplicativos avaliados: planejamento_do_projeto/lista-apps-avaliados.md
    - Aplicativo selecionado: planejamento_do_projeto/app-selecionado.md
    - Rich Picture: planejamento_do_projeto/rich-picture.md
    - Inspeções:
      - "Lista de inspeção": planejamento_do_projeto/listainspecao.md
      - "Inspeção do grupo": planejamento_do_projeto/inspecaogrupo.md
      - "Inspeção do grupo + 1 (Grupo 07)": planejamento_do_projeto/inspecaogrupo+1.md
  - Elicitação de Requisitos:
    - Definição do Perfil de Usuário: elicitacao/perfil_usuario.md
    - Personas: elicitacao/personas.md
    - Elicitação de Requisitos: 
      - "Encenação": elicitacao/encenacao.md
      - "Entrevista": elicitacao/entrevista.md
      - "Introspecção": elicitacao/introspeccao.md
    - Requisitos Elicitados: elicitacao/requisitos_elicitados.md
    - Priorização de Requisitos: elicitacao/priorizacao_requisitos.md
    
theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: green

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: green
    - scheme: high-contrast
      primary: black
      accent: yellow
      toggle:
        icon: material/weather-cloudy-alert
        name: Switch to high contrast
  logo: imagens/logoinss.svg
  extra_css: [stylesheets/extra.css]
