repo_url: https://github.com/Requisitos-de-Software/2024.2-Grupo06
repo_name: 2024.2-Grupo06
site_name: Meu INSS
nav:
  - Home: index.md
  - Atas:
    - Reunião 1: atas/Reuniao01_23.10.2024.md
    - Reunião 2: atas/Reuniao02_26.10.2024.md
    - Reunião 3: atas/Reuniao03_15.11.2024.md
    - Reunião 4: atas/Reuniao04_21.11.2024.md
    - Reunião 5: atas/Reuniao05_28.11.2024.md
    - Reunião 6: atas/Reuniao06_10.12.2024.md
    - Reunião 7: atas/Reuniao07_09.01.2025.md
  - Apresentação:
    - Apresentação 1: apresentacoes/apresentacao1.md
    - Apresentação 2: apresentacoes/apresentacao2.md
    - Apresentação 3: apresentacoes/apresentacao3.md
    - Apresentação 4: apresentacoes/apresentacao4.md
    - Apresentação 6: apresentacoes/apresentacao6.md
  - Planejamento do Projeto:
    - Heatmap de disponibilidade: planejamento_do_projeto/heatmap-disponibilidade.md
    - Cronograma planejado: planejamento_do_projeto/cronograma_planejado.md
    - Cronograma executado: planejamento_do_projeto/cronograma_executado.md
    - Ferramentas do projeto: planejamento_do_projeto/ferramentas.md
    - Aplicativos avaliados: planejamento_do_projeto/lista-apps-avaliados.md
    - Aplicativo selecionado: planejamento_do_projeto/app-selecionado.md
    - Rich Picture: planejamento_do_projeto/rich-picture.md
    - Inspeções:
      - "Lista de inspeção": planejamento_do_projeto/listainspecao.md
      - "Inspeção do grupo": planejamento_do_projeto/inspecaogrupo.md
      - "Inspeção do grupo + 1 (Grupo 07)": planejamento_do_projeto/inspecaogrupo+1.md
  - Elicitação de Requisitos:
    - Definição do Perfil de Usuário:
      - "Perfil de usuário": elicitacao/Perfil_Do_Usuario.md
      - "Questionário": elicitacao/Questionario.md
    - Personas: elicitacao/personas.md
    - Elicitação de Requisitos: 
      - "Cronograma de elicitação": elicitacao/cronogramaelicitacao.md
      - "Encenação": elicitacao/encenacao.md
      - "Entrevista": elicitacao/entrevista.md
      - "Introspecção": elicitacao/introspeccao.md
      - "Observação": elicitacao/observacao.md
      - "Glossário": elicitacao/glossario.md
    - Requisitos Elicitados: elicitacao/requisitos_elicitados.md
    - Priorização de Requisitos: 
      - "Cronograma de priorização": elicitacao/cronogramapriorizacao.md
      - "First Things First": elicitacao/first_things_first.md
      - "Three Level Scale": elicitacao/three_level_scale.md
      - "$100": elicitacao/100dol.md
    - Inspeções:
      - "Lista de inspeção": elicitacao/listainspecao.md
      - "Inspeção do grupo": elicitacao/inspecao.md
      - "Inspeção do grupo + 1 (Grupo 07)": elicitacao/inspecaogrupo+1.md
  - Modelagem de Requisitos - Parte 1:
    - "Casos de Uso": modelagem_parte1/casosdeuso.md
    - "Validação dos Casos de Uso": modelagem_parte1/validacaoCasodeUso.md
    - "Cenários": modelagem_parte1/cenarios.md
    - "Léxicos": modelagem_parte1/lexicos.md
    - "Especificação Suplementar": modelagem_parte1/especificacaosuplementar.md
    - Inspeções:
      - "Lista de inspeção": modelagem_parte1/listadeinspecao3.md
      - "Inspeção do grupo": modelagem_parte1/inspecaogrupo.md
      - "Inspeção do grupo + 1 (Grupo 07)": modelagem_parte1/inspecaogrupo+1.md
  - Modelagem de Requisitos - Parte 2:
    - "Backlog": modelagem_parte2/backlog.md
    - "Histórias de Usuário": modelagem_parte2/historias.md
    - "NFR Framework": modelagem_parte2/nfr.md
    - Inspeções:
      - "Lista de inspeção": modelagem_parte2/listainspec4.md
      - "Inspeção do grupo": modelagem_parte2/inspec4grupo.md
      - "Inspeção do grupo + 1 (Grupo 07)": modelagem_parte2/inspecaogrupo+1.md
  - Pós-rastreabilidade:
    - "Matriz de rastreabilidade": rastreabilidade/matriz.md
    - "Backward from": rastreabilidade/backward-from.md
    - "Foward from": rastreabilidade/foward.md
    - Inspeções:
      - "Lista de inspeção": rastreabilidade/Inspecao6/listainspec5.md
      - "Inspeção do grupo": rastreabilidade/Inspecao6/inspecaogrupo.md
      - "Inspeção do grupo + 1 (Grupo 07)": rastreabilidade/Inspecao6/inspecaogrupo+1.md
  - Validação:
    - "RF 28 - Agendar horário em uma agência do INSS": validacao/validacao1/RF28.md
    - "RF 25 - Consulta e pagamento de pensões": validacao/validacao1/RF25.md
  - Verificação:
    - Etapa 1:
        - Planejamento da verificação: verificacao/Grupo6/Entrega 1/Planejamento da Verificação.md
        - RichPicture: verificacao/Grupo6/Entrega 1/RichPicture.md
        - Heatmap: verificacao/Grupo6/Entrega 1/Heatmap de Disponibilidade.md
        - Ferramentas: verificacao/Grupo6/Entrega 1/Ferramentas.md
        - Cronograma Planejado: verificacao/Grupo6/Entrega 1/Cronograma Planejado.md
        - Cronograma Executado: verificacao/Grupo6/Entrega 1/Cronograma Executado.md
        - Aplicativos Avaliados: verificacao/Grupo6/Entrega 1/Aplicativos Avaliados.md
        - Aplicativo Selecionado: verificacao/Grupo6/Entrega 1/Aplicativo Selecionado.md
    - Etapa 2:
        - Planejamento da verificação: verificacao/Grupo6/Entrega 2/planejamento.md
        - Perfil de usuário: verificacao/Grupo6/Entrega 2/perfildeusuario.md
        - Personas: verificacao/Grupo6/Entrega 2/personas.md
        - Encenação: verificacao/Grupo6/Entrega 2/encenacao.md
        - Entrevista: verificacao/Grupo6/Entrega 2/entrevista.md
        - Introspecção: verificacao/Grupo6/Entrega 2/introspeccao.md
        - Observação: verificacao/Grupo6/Entrega 2/observacao.md
        - Glossário: verificacao/Grupo6/Entrega 2/glossario.md
        - First Things First: verificacao/Grupo6/Entrega 2/firstthingsfirst.md
        - Three Level Scale: verificacao/Grupo6/Entrega 2/threelevelscale.md
        - $100: verificacao/Grupo6/Entrega 2/100dol.md
    - Etapa 3:
        - Planejamento da verificação: verificacao/Grupo6/entrega3/planejamento.md
        - Casos de Uso: verificacao/Grupo6/entrega3/casodeuso.md
        - Validação dos Casos de Uso: verificacao/Grupo6/entrega3/validcasodeuso.md
        - Cenários: verificacao/Grupo6/entrega3/cenarios.md
        - Léxicos: verificacao/Grupo6/entrega3/lexicos.md
        - Especificação suplementar: verificacao/Grupo6/entrega3/espsuplementar.md
    - Etapa 4:
        - Planejamento da verificação: verificacao/Grupo6/entrega3/Planejamento da Verificação.md
    - Etapa 6:
        - Planejamento da verificação: verificacao/Grupo6/entrega6/planejamento.md
        - Matriz de rastreabilidade: verificacao/Grupo6/entrega6/matriz.md
        - Backward-from: verificacao/Grupo6/entrega6/backward.md
        - Forward-from: verificacao/Grupo6/entrega6/forward.md




    
theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: green

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: green
    - scheme: high-contrast
      primary: black
      accent: yellow
      toggle:
        icon: material/weather-cloudy-alert
        name: Switch to high contrast
  logo: imagens/logoinss.svg
  extra_css: [stylesheets/extra.css]
