repo_url: https://github.com/Requisitos-de-Software/2024.2-Grupo06
repo_name: 2024.2-Grupo06
site_name: Meu INSS
nav:
  - Home: index.md
  - Atas:
    - Reunião 1: atas/Reuniao01_23.10.2024.md
    - Reunião 2: atas/Reuniao02_26.10.2024.md
  # - Apresentação: index.md
  - Planejamento do Projeto:
    - Heatmap de disponibilidade: planejamento_do_projeto/heatmap-disponibilidade.md
    - Ferramentas do projeto: planejamento_do_projeto/ferramentas.md
    - Aplicativos avaliados: planejamento_do_projeto/lista-apps-avaliados.md
    - Aplicativo selecionado: planejamento_do_projeto/app-selecionado.md
    - Rich Picture: planejamento_do_projeto/rich-picture.md
    - Cronograma planejado: planejamento_do_projeto/cronograma_planejado.md
    - Cronograma executado: planejamento_do_projeto/cronograma_executado.md
theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: green

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: green
    - scheme: high-contrast
      primary: black
      accent: yellow
      toggle:
        icon: material/weather-cloudy-alert
        name: Switch to high contrast
  logo: imagens/logoinss.png
  extra_css: [stylesheets/extra.css]
